project:
  type: website

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
        
      # START OF DROPDOWN
      - text: "Analysis"  # This is the name of the dropdown button
        menu:
          - text: "Stride Fallacy"
            href: analysis.qmd
          - text: "Slot Efficencey"
            href: analysis2.qmd
          - text: "Push Off"
            href: analysis3.qmd
          - text: "The Hips Do Lie"
            href: analysis4.qmd
          - text: "Elbow Torque"
            href: analysis5.qmd
      - href: takeaways.qmd
        text: Actionable Takeaways   
      - href: about.qmd
        text: About

  page-footer:
    background: "#2E5A38"  # Outfield Green
    foreground: "#FDFBF7"  # Cream Text (for readability)
    center: "Grayson Medico | [Link to Data Source](https://github.com/drivelineresearch/openbiomechanics/tree/main/baseball_pitching/data)"

format:
  html:
    theme:
      - cosmo  # or any base theme you like
      - custom.scss
    toc: true


