project:
  type: website

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
        
      # START OF DROPDOWN
      - text: "Analysis"  # This is the name of the dropdown button
        menu:
          - text: "Stride Fallacy"
            href: analysis.qmd

      - href: about.qmd
        text: About This Project

  page-footer:
    background: "#2E5A38"  # Outfield Green
    foreground: "#FDFBF7"  # Cream Text (for readability)
    center: "Grayson Medico | [Link to Data Source](https://github.com/drivelineresearch/openbiomechanics/tree/main)"

format:
  html:
    theme:
      - cosmo  # or any base theme you like
      - custom.scss
    toc: true


